/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlincoroutinetracingissuerepro

import org.slf4j.LoggerFactory
import scenario

val logger = LoggerFactory.getLogger("main")

fun main() {
    logger.info("start")
    scenario()
    logger.info("finish")
}
