/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlincoroutinetracingissuerepro

import scenario


fun main() {
    println("start")
    scenario()
    println("finish")
}
